kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'html-openshift-app:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:1.20-ubi7'
  source:
    type: Git
    git:
      uri: 'https://github.com/Dbelviso/Aufgabe-6.2'
    contextDir: /app/web
    sourceSecret:
      name: html-openshift-app-github
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: html-openshift-app-generic-webhook-secret
    - type: ImageChange
    - type: ConfigChange
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
