kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: RGJlbHZpc28=
  password: Z2hwX09zeVFNZ294ZUp4MXlESlVrTmdhZHRVcFFKOFNWdDFsc2dWaw==
type: kubernetes.io/basic-auth
 
 