apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part: html-openshift-app
spec:
  lookupPolicy:
    local: false
